# Generated by Django 5.2 on 2025-05-15 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCarteConsulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Numéro de dossier')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=20)),
                ('nationalite', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('photo_identite', models.ImageField(upload_to='documents/photos_identite/')),
                ('piece_identite', models.FileField(upload_to='documents/pieces_identite/')),
                ('justificatif_domicile', models.FileField(upload_to='documents/justificatifs_domicile/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'En cours de traitement'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('commentaires', models.TextField(blank=True, help_text='Commentaires internes de l’administration', null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de carte consulaire',
                'verbose_name_plural': 'Demandes de cartes consulaires',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
